apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoshare-backend
  namespace: ecoshare
  labels:
    app: ecoshare-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecoshare-backend
  template:
    metadata:
      labels:
        app: ecoshare-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/ziedtabib/ECOSHARE/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: ecoshare-secrets
                  key: mongodb-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecoshare-secrets
                  key: jwt-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ecoshare-backend-service
  namespace: ecoshare
spec:
  selector:
    app: ecoshare-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
